### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by drawned** [nulli0n/ExcellentEnchants-spigot#1]
[14:32:17 ERROR]: Could not pass event EntityDamageByEntityEvent to ExcellentEnchants v3.0.9
net.minecraft.ResourceKeyInvalidException: Non [a-z0-9/._-] character in path of location: minecraft:ENTITY_FIREWORK_ROCKET_LAUNCH

Paper 1.17.1

**Comment by nulli0n** [comment]
Use the latest plugin version
