### ISSUE TITLE
Equations in description

### ISSUE THREAD

**Issue by LevMan7** [nulli0n/ExcellentEnchants-spigot#100]
![image](https://github.com/nulli0n/ExcellentEnchants-spigot/assets/80598406/8f72727f-f552-4397-a4f2-72746d2ed94c)
![image](https://github.com/nulli0n/ExcellentEnchants-spigot/assets/80598406/f89b7b70-d412-4428-9b0d-ca54aea12078)

I need to use it here. It's not working right now. in this place, I can only use %enchantment_exp_modifier%, and it consists of 3 numbers, and I want to have a single digit. 👨‍💻

**Comment by nulli0n** [comment]
Just use the latest plugin version with %modifier% placeholder.
