### ISSUE TITLE
Unable to charge custom enchants applied to Itemsadder weapons

### ISSUE THREAD

**Issue by SlyGuy89** [nulli0n/ExcellentEnchants-spigot#101]
Enchantments apply and function as expected without the charge system, but when the charge system is active I cannot recharge the enchants applied to an Itemsadder weapon. It only shows a red X on the anvil.

I've tested with other custom model items not from Itemsadder, and I have no issues applying or charging the enchantments.

Is there a compatibility issue with Itemsadder? Or is it possible I made a mistake during the update? I did delete and re-generate the main Config file and the Enchants folder so I'd be working with fresh configurations.

Thanks in advance for your time!

**Comment by nulli0n** [comment]
You have to ask ItemsAdder about this.

**Comment by SlyGuy89** [comment]
Oh darn my bad I meant to close that ticket, sorry!!

Yahoo Mail: Search, Organize, Conquer 
 
  On Mon, Apr 22, 2024 at 5:35 AM, ***@***.***> wrote:   


You have to ask ItemsAdder about this.
