### ISSUE TITLE
Villagers do not give new enchants

### ISSUE THREAD

**Issue by BlazingPatriot** [nulli0n/ExcellentEnchants-spigot#106]
I have the config set to vanilla distribution and from what I can tell it should generate the new enchants in villager trades but for me it does not. Enchants are generated in loot tables and enchanting tables but just not villager trades. I've broken over 670 lectures trying to get these new enchants. Please let me know what im doing wrong

**Comment by nulli0n** [comment]
Latest MC versions uses rebalanced villager trades with predefiend enchanted books. Nothing wrong here.

**Comment by BlazingPatriot** [comment]
Dang it, thank you. Is there any way that you know of that can change that?

**Comment by nulli0n** [comment]
No, unfortunately. You can look for villager trade editor plugins.
