### ISSUE TITLE
This is a sinicization of Chinese Simplified

### ISSUE THREAD

**Issue by BigAppleClass** [nulli0n/ExcellentEnchants-spigot#111]
Dear author, this is a Chinese Simplified Chinese configuration file from China, I hope you can add it to the configuration folder of the plugin for users who need Chinese Simplified. It's free, I hope you can add the name of this Chinese translator: Chaliang_. Thank you.

[enchants-zh_CN.zip](https://github.com/user-attachments/files/15764425/enchants-zh_CN.zip)

**Comment by nulli0n** [comment]
Yes, thanks!
