### ISSUE TITLE
Cannot read field "k" because "enchantmentMenu" is null

### ISSUE THREAD

**Issue by cloakfox** [nulli0n/ExcellentEnchants-spigot#113]
https://gist.github.com/cloakfox/b0c9709acf0b3bf657c06e1917a93413

Currently using ExcellentEnchants 4.1.0 (these errors have been popping up on older versions too) with paper 1.20.4 (AxolotlSpigot)

**Comment by nulli0n** [comment]
No idea what AxolotlSpigot is. Use supported server software.

**Comment by cloakfox** [comment]
> No idea what AxolotlSpigot is. Use supported server software.

What about paper?

**Comment by cloakfox** [comment]
bump

**Comment by lucreista** [comment]
have same issue with paper 1.20.4

**Comment by nulli0n** [comment]
Use 1.21.1 and v4.2.0
