### ISSUE TITLE
packetevents migration

### ISSUE THREAD

**Issue by HaHaWTH** [nulli0n/ExcellentEnchants-spigot#114]
ProtocolLib is unfortunately no longer very active and the updates take longer and longer and unfortunately often no longer work satisfactorily. PacketEvents is another actively maintained packet processing library.

PacketEvents repository: https://github.com/retrooper/packetevents

**Comment by nulli0n** [comment]
Ok I will consider

**Comment by nulli0n** [comment]
Added
