### ISSUE TITLE
excellentenchants crashes clients when certain chests are generated

### ISSUE THREAD

**Issue by bruhhhwarrior** [nulli0n/ExcellentEnchants-spigot#116]
Hello, 
when a player generates a chest's content it can crash the server. 
In my case it happened when generating the chest's content in bastions and ruined nether portals.
https://mclo.gs/28jstvN

There are sadly 0 console errors so all i can provide is that client log.
Im 100% sure its being caused by the excellentenchants plugin as i narrowed it down with binary search, https://docs.papermc.io/paper/basic-troubleshooting#binary-search

This error does not happen when the ways.LOOT_GENERATION.enabled = false
So i believe there to be an issue in the generation.

here is a spark log if that could help in anyway: https://spark.lucko.me/62yUNvpwNR

**Comment by nulli0n** [comment]
You can't use it in 1.20.6, update to 1.21.1
