### ISSUE TITLE
The plugin is causing sever crash and disconnects the player

### ISSUE THREAD

**Issue by Jiejue233** [nulli0n/ExcellentEnchants-spigot#120]
## Using versions
* Minecraft: ```This server is running Paper version 1.20.6-148-ver/1.20.6@20f5165 (2024-07-02T15:37:33Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)```
* NightCore: nightcore-2.6.3
* ProtocolLib: v5.2.0
* ExcellentEnchantment: ExcellentEnchants-4.1.0
* Java: 21

### Possible conflict plugins:
* Slimefun: RC-37
* SlimeTinker (slimefun addon): DEV-84
* InfernalMobs: 6.7.6
* McMMO: 2.2.016

### attempt 1
1. wearing a full set of armour with enchantment on each piece
2. add ExcellentEnchantment (and all the required plugins) to the plugin folder, restart the server
3. login the server
4. the player is disconnected immediately, and an exception pops up 
`Internal Exception: io.netty.handler.codec.DecoderException; Failed to decode packet 'clientbound/minecraft:set_equipment'`
5. all the following login failed with just repeating 3 and 4

### attempt 2
1. removed every possible enchanted armour and tools/weapon out of wearing and inventory, clear all the buffs no matter if granted from SlimeFun or potions
2. add ExcellentEnchantment (and all the required plugins) to the plugin folder, restart the server
3. login the server
4. successfully logged in and be able to move
5. when opening the enchantment table, the player is disconnected immediately and the same exception shows up
6. any following login failed and the player got disconnected.

## additional information
there are no errors reported on the console during all the procedures above, allares just clientside disconnections

**Comment by fffzzl** [comment]
This plugin cannot runing on 1.20.6
