### ISSUE TITLE
Custom enchants dont generate from structures and fishing since 1.21

### ISSUE THREAD

**Issue by AdaptableRuben** [nulli0n/ExcellentEnchants-spigot#123]
I have a server, and players have spend hundred of hours trying to find some of the enchantments I set for treasure only but they pretty much came empty handed with only vanilla enchants, they also tried fishing which I have enabled but also it didnt work and only came out with normal vanilla enchants.

This mean that there is a bug which causes custom enchants from looting structures and fishing to not generate unfortunately because I set the chances so high that is should be impossible to get none from spending multiple hours in finding them. 

[pebblehost-588841-pzxtsx.zip](https://github.com/user-attachments/files/16550316/pebblehost-588841-pzxtsx.zip)

This zip file contains the config I currently have set up in my server. So you can test it since I have no idea if theres something wrong in the config, since last time I checked, everthing was right from what I read in it, so its likely to be a bug.

**Comment by nulli0n** [comment]
Use v4.2.0
