### ISSUE TITLE
[BUG] Mining STONE block with smelter enchant don't drop smooth_stone

### ISSUE THREAD

**Issue by OMarcoGPO** [nulli0n/ExcellentEnchants-spigot#124]
When you mine a stone block, the enchant smelter drop stone, it should drop smooth_stone

Plugin Version: 4.1.0
Paper 1.21

**Comment by nulli0n** [comment]
It's excluded by default. Check config before post issues.

**Comment by OMarcoGPO** [comment]
Hi, I should had post you the following:
![image](https://github.com/user-attachments/assets/68d44d15-238f-4afc-939a-35f475123851)

So I did desactivated the stone from it

More clear information:
When I mine the stone the enchant work beacuse it display the flame particles, but it drop stone anyway

Maybe the format of my config file is not the correct, so I asume that '[]' could work to set nothing to the list

Hope this makes clear that the issue is happening
