### ISSUE TITLE
[Bug] Variables do not work in the enchantment info menu.

### ISSUE THREAD

**Issue by ChrisTVH** [nulli0n/ExcellentEnchants-spigot#131]
### Server information
-  UniverseSpigot version `1.21-DEV-ver/1.21@de86e12 (2024-08-30T06:48:45Z)`
- ExcellentEnchants `4.2.1`
### Bug information
When opening the enchantment information menu, the obtain and name variables do not work.
### Images
![image](https://github.com/user-attachments/assets/eabb8ebb-d727-4267-b90c-bbd49dadda86)
![image](https://github.com/user-attachments/assets/108ce68a-d560-4e11-af14-c7258f857b1a)

**Comment by nulli0n** [comment]
1. %enchantment_name%
2. Not a thing anymore

**Comment by ChrisTVH** [comment]
At least warn in the changelog, to regenerate the configuration.
