### ISSUE TITLE
Bug: enchanting with level 0 or less than 0 won't remove the enchantment from an item

### ISSUE THREAD

**Issue by NyaomiDEV** [nulli0n/ExcellentEnchants-spigot#133]
As the title says, it's impossible to remove an enchant from an item.
Using Paper on 1.21.1, EE version 4.2.1

**Comment by NyaomiDEV** [comment]
I took a look at the code and, indeed, there seems to be a conflict of implementation, as the item level will be random if it's specified as less than 1.

**Comment by nulli0n** [comment]
Fixed in v4.2.2
