### ISSUE TITLE
[BUG] Lores are duplicating when using an anvil to repair an item

### ISSUE THREAD

**Issue by shifhu1234** [nulli0n/ExcellentEnchants-spigot#14]
**When I /kit an item, for example a pickaxe with Tunnel I, I use it (loses some durability) then try to repair the item in an anvil, the lores on the item are duplicating. (There'll be 2 lines of Tunnel I)**
_If I trade the item in a villager, usually no bug happens._

Please, contact me if you found a fix to it!
Thank you.

**Comment by nulli0n** [comment]
It's a plugin conflict. Nothing to do on my side.
