### ISSUE TITLE
[Question] API for developers

### ISSUE THREAD

**Issue by mehboss** [nulli0n/ExcellentEnchants-spigot#142]
Hello there,
Do you have a maven repo or an API I can utilize to add plugin support?

I have attempted this, but to be honest, it is a pretty big task to go through all of the classes to find the correct methods.
![image](https://github.com/user-attachments/assets/5e435c16-7de0-44b1-9390-be2379e6124f)
Thank you

**Comment by nulli0n** [comment]
There is no maven repo, all you can do is install it from .jar to your local maven repo.
