### ISSUE TITLE
Conflict between excellentenchants, oraxen, and protocollib

### ISSUE THREAD

**Issue by thatpris** [nulli0n/ExcellentEnchants-spigot#143]
When Oraxen and Protocolib plugins are installed, enchants from excellentnenchants cannot be applied to items in anvil.

**Steps to reproduce the behavior:**
1. Join with Paper 1.21.1 with Oraxen, Protocolib and ExcellentEnchants
2. Get an enchantment book from ExcellentEnchants
3. Apply it to an item in anvil
4. Bug occurs

https://github.com/user-attachments/assets/3e4228a7-addd-417f-9352-bfe5f2118ed1

**Comment by thatpris** [comment]
Seems like the bug is coming from ExcellentEnchants plugin's side,
github.com/oraxen/oraxen/issues/1528

**Comment by nulli0n** [comment]
Perhaps it was fixed by Oraxen now?

**Comment by thatpris** [comment]
yep :)
