### ISSUE TITLE
[Request] Bow enchant - Arrows place torches where they land.

### ISSUE THREAD

**Issue by thantik** [nulli0n/ExcellentEnchants-spigot#20]
I've always wanted something to be able to kind of put torches on the roofs of my caves.  Doesn't really make sense for me to build up to them and then place torches, and come back down.  Would love to be able to fire an arrow with a bow that has an enchantment like this and light up ceilings, from a distance away.  It should use the torches in your inventory to work, there's a drawback that if your arrow doesn't land on a surface that can have a torch added - it just doesn't add it.  This could be a good balancing mechanic.  Additionally - I've always seen old movies where there's a war, it's dark - and some massive army lights up a bunch of fire arrows only to later have them dotting the landscape still on fire later on.

**Comment by nulli0n** [comment]
Sounds cool, will be implemented in the next update! Sorry for such late respsonse.

**Comment by nulli0n** [comment]
Added in v3.5.0!
