### ISSUE TITLE
[Request] Shield Enchantment Redirection

### ISSUE THREAD

**Issue by LadyHaley** [nulli0n/ExcellentEnchants-spigot#24]
Enchantment that Reflects different projectiles off of a blocking shield
Any projectile that hits a blocking shield, gets redirected at varied levels of velocity and accuracy back towards where the player is aiming. Items including TNT (If its moving fast enough), Ender pearls, Potions, Arrows, Fireballs 
Maybe even elytra users flying into the shield

**Comment by nulli0n** [comment]
Not planned, sorry.
