### ISSUE TITLE
[Bug] Possible error with regrowth enchantment

### ISSUE THREAD

**Issue by LadyHaley** [nulli0n/ExcellentEnchants-spigot#26]
I think theres an error with the regrowth enchantment where a play can take damage at the same time healing, if the damage was enough to kill the player before healing, the death screen will show, but because of the healing the player will not be dead, despite the death screen showing. This might occur due to the high ping that occurs between the US and Australian, but I'm not certain.

**Comment by LadyHaley** [comment]
This error is happening every time I die with the Regrowth Enchant on

**Comment by nulli0n** [comment]
Yes, will be fixed.

**Comment by nulli0n** [comment]
Fixed in the latest update.
