### ISSUE TITLE
Applying enchantments via Anvil and books does not work

### ISSUE THREAD

**Issue by Gustiviy** [nulli0n/ExcellentEnchants-spigot#27]
Using books from the `/eenchants book `command and attempting to apply them via anvil does not work
![image](https://user-images.githubusercontent.com/79268434/194396964-004dde64-c2f5-4d09-8c8e-a18047b3ad5b.png)

NexEngine is the latest version and plugin version is 3.2.7

**Comment by nulli0n** [comment]
Probably a plugin conflict. Try it on a clean server.
