### ISSUE TITLE
Fire Walking No Longer working when Upgrading to 1.19.2

### ISSUE THREAD

**Issue by mistermsk** [nulli0n/ExcellentEnchants-spigot#28]
I upgraded to Paper 1.19.2 from 1.19. Also, upgraded NextEngine and ExcellentEnchants to most recent version. Additionally, updated ProtocolLibs to most recent dev version. Most enchants seem to work. However, Fire Walker doesn't seem to work anymore. When you walk next to lava, it no longer turns into a magma block. I went back to an older version of ProtocolLibs and still not working. Seeing if any help could be given.

**Comment by nulli0n** [comment]
Fixed.
