### ISSUE TITLE
[Feature Request] Ability to have right click power and custom model

### ISSUE THREAD

**Issue by DeathGOD7** [nulli0n/ExcellentEnchants-spigot#3]
I recently stumbled with your ExcellentCrates plugin...then I went to its wiki and saw a whole bunch of my desired needs plugins like custom currency, custom enchants, authentication, daily bonus, money hunters (for rewards for doing stuff), and sunlight for managing servers.

I really really wanna thank you for creating all these great plugins.

If you can add the ability to add right-click power and custom model to excellent enchants then it will be bigger than executable items. Also I love the feature of wide varieties of customization in all your plugin.

Anyway be safe in these times and have a nice day.

Regards,
Death GOD 7

**Comment by nulli0n** [comment]
Not the plugin purpose. Won't be implemented.
