### ISSUE TITLE
Plugins fails to start

### ISSUE THREAD

**Issue by Chris6ix** [nulli0n/ExcellentEnchants-spigot#32]
ExcellentEnchants fails to start with the following error in the console:
![image](https://user-images.githubusercontent.com/65610536/206294353-38c1b22e-7eb0-49ca-b3f7-ad238d5a6512.png)

**Comment by FoxPodZ** [comment]
Create a batch script which creates a file with last Bluescreen of Death information I had the same issue. Try Updating NexEngine and try again

**Comment by FoxPodZ** [comment]
I had the same issue. Try re-downloading the latest version of NexEngine

**Comment by Chris6ix** [comment]
Alright I will try that, thank you
