### ISSUE TITLE
Could not pass event EntityExplodeEvent to ExcellentEnchants v3.2.8

### ISSUE THREAD

**Issue by Danila767** [nulli0n/ExcellentEnchants-spigot#33]
Tested Java 17 & 18, ExcellentEnchants v3.2.8, latest NexEngine
[log.txt](https://github.com/nulli0n/ExcellentEnchants-spigot/files/10199494/log.txt)

**Comment by nulli0n** [comment]
Don't use Blast Mining and Tunnel together, they're incompatible.

**Comment by Danila767** [comment]
> Don't use Blast Mining and Tunnel together, they're incompatible.

Maybe we should forbid combining these enchantments? How?

**Comment by nulli0n** [comment]
It's already marked as conflict to each other. There is an option 'Conflicts' in each enchantment config.

**Comment by nulli0n** [comment]
Fixed.
