### ISSUE TITLE
ExcellentEnchants no longer spawn on villager and enchanting_table after the update

### ISSUE THREAD

**Issue by BigAppleClass** [nulli0n/ExcellentEnchants-spigot#35]
After I plugged the jar into plugins, the Villager and enchanting_table didn't spawn ExcellentEnchants , but they did.     I couldn't link to discord, so I had to go here and ask

spigot1.19.2

**Comment by nulli0n** [comment]
Visual bug. Wait for an update.

**Comment by nulli0n** [comment]
Fixed in the latest update.
