### ISSUE TITLE
Villager discount not longer show with plugin active

### ISSUE THREAD

**Issue by Ammutadori075** [nulli0n/ExcellentEnchants-spigot#38]
I have a problem that arose after installing one of the latest versions but still present in the latest. 
With the plugin active, villagers no longer show, even if discounts are applied, the discounts once healed from zombie villager to villager.
The problem does not occur if I start the server without the plugin active.

**Comment by Ammutadori075** [comment]
Problem started from version 3.3.0 and still present in 3.3.0.4 version

**Comment by Texbio** [comment]
Also having this issue.

**Comment by nulli0n** [comment]
Fixed in v3.4.0
