### ISSUE TITLE
Lore via ProtocolLib seems to not work using Paper 1.19.3

### ISSUE THREAD

**Issue by NyaomiDEV** [nulli0n/ExcellentEnchants-spigot#39]
![image](https://user-images.githubusercontent.com/13177694/221420841-6e68e109-b62f-4feb-9ad0-2e03ea07f92c.png)

Note: this bow was obtained prior to today's plugin release, and it should have the Withered Arrows enchantment on it.

**Comment by NyaomiDEV** [comment]
Okay I investigated a bit. Triggering a reload via `/eenchants reload` seems to work around this issue, but then all the players need to log out and in again. It simply seems that the ProtocolLib stuff doesn't work on first startup.

**Comment by nulli0n** [comment]
Fixed.
