### ISSUE TITLE
[BUG] Player Heads Random extra nbt data

### ISSUE THREAD

**Issue by Texbio** [nulli0n/ExcellentEnchants-spigot#42]
excellent enchants is giving player heads extra nbt data for no reason:

{
  "PublicBukkitValues": {
    "excellentenchants:lore_size": 0
  }
}

to replicate: place a player head, break it, pick it up, see that it does not stack with the same player heads and if using a tool to view nbt data you can see that it adds extra nbt data.

I would request that when fixed, player heads with this tag that get broken get this tag removed because it does not belong on those player heads.
This is pretty annoying with the slimefun4 plugin because it utilizes player heads for a system called cargo, and when stuff does not stack it seems like something is wrong with the item.

**Comment by Texbio** [comment]
hello?

**Comment by nulli0n** [comment]
Will be fixed in the next update

**Comment by nulli0n** [comment]
Fixed.
