### ISSUE TITLE
error with your plugin

### ISSUE THREAD

**Issue by games4681** [nulli0n/ExcellentEnchants-spigot#47]
[WARNING] .... Exception in thread "Paper Watchdog Thread" java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.ints.IntArrayList.getInt(int)" because "this.wrapped" is null

[WARNING] .... at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$MapIterator.nextEntry(Int2ObjectOpenHashMap.java:657)

[WARNING] .... at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$ValueIterator.next(Int2ObjectOpenHashMap.java:1164)

[WARNING] .... at net.minecraft.server.level.PlayerChunkMap.b(PlayerChunkMap.java:1240)

[WARNING] .... at net.minecraft.server.level.ChunkProviderServer.a(ChunkProviderServer.java:914)

[WARNING] .... at net.minecraft.server.level.WorldServer$a.f(WorldServer.java:2615)

[WARNING] .... at net.minecraft.server.level.WorldServer$a.b(WorldServer.java:2503)

[WARNING] .... at io.papermc.paper.chunk.system.entity.EntityLookup.entityStatusChange(EntityLookup.java:279)

[WARNING] .... at io.papermc.paper.chunk.system.entity.EntityLookup$EntityCallback.a(EntityLookup.java:823)

[WARNING] .... at net.minecraft.world.entity.Entity.b(Entity.java:4546)

[WARNING] .... at net.minecraft.world.entity.Entity.a(Entity.java:679)

[WARNING] .... at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:742)

[WARNING] .... at net.minecraft.world.entity.player.EntityHuman.a(EntityHuman.java:1496)

[WARNING] .... at net.minecraft.server.level.WorldServer.a(WorldServer.java:1561)

[WARNING] .... at net.minecraft.server.players.PlayerList.remove(PlayerList.java:638)

[WARNING] .... at net.minecraft.server.network.PlayerConnection.onDisconnect(PlayerConnection.java:2121)

[WARNING] .... at net.minecraft.server.network.PlayerConnection.disconnect(PlayerConnection.java:533)

[WARNING] .... at net.minecraft.server.network.PlayerConnection.disconnect(PlayerConnection.java:474)

[WARNING] .... at net.minecraft.server.players.PlayerList.removeAll(PlayerList.java:1331)

[WARNING] .... at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:959)

[WARNING] .... at net.minecraft.server.dedicated.DedicatedServer.t(DedicatedServer.java:804)

[WARNING] .... at net.minecraft.server.MinecraftServer.close(MinecraftServer.java:902)

[WARNING] .... at org.spigotmc.WatchdogThread.run(WatchdogThread.java:233)

**Comment by nulli0n** [comment]
Fixed in v3.4.2
