### ISSUE TITLE
[Bug Report] Book Enchants not working

### ISSUE THREAD

**Issue by LadyHaley** [nulli0n/ExcellentEnchants-spigot#49]
Book enchants dont seem to be working, they wont transfer to a weapon when spawned in and used in an anvil. I can combine one custom enchantment to a vanilla enchant book, but any more custom enchants override the previous custom enchant. using a book with a vanilla enchant and a custom enchant to enchant an item will not give that item the custom enchantment. Using commands to enchant the item that was enchanted with the book, works for giving the item the enchantment

**Comment by nulli0n** [comment]
Could you provide a video of this?
