### ISSUE TITLE
[Bug Report] Lore is erased when disenchanting and enchanting.

### ISSUE THREAD

**Issue by KellerThompson** [nulli0n/ExcellentEnchants-spigot#55]
This bug causes the lore previously attached to an item to be erased when enchanting it. 

The way to recreate it is as follows: 

1. Have an item with a custom lore.
2. Enchant the item with any plugin enchantment. 
3. Disenchant the item using a grindstone.
4. Enchant the item again with another custom enchantment.

 I believe the problem is that when disenchanting, the "excellentenchants:lore_size" tag is not being erased, although I'm not entirely sure.

**Comment by nulli0n** [comment]
Fixed in v3.5.0!
