### ISSUE TITLE
[Bug report] Tunnel enchant in shovel when using aurelium skill can crash the server

### ISSUE THREAD

**Issue by FurrO2** [nulli0n/ExcellentEnchants-spigot#56]
[2023-07-04-1.log](https://github.com/nulli0n/ExcellentEnchants-spigot/files/11951300/2023-07-04-1.log)

Here the log:

Hello dev!
Today, while using a shovel with tunnel and some mana from aurelium skill ( terraform ), my server crashed..
Can you help me ? 
( i'm not using the lattest version of excellentEnchant and aurelium skill )

Thanks.

**Comment by nulli0n** [comment]
Report to AureliumSkills.
