### ISSUE TITLE
[Request] Warden Enchantments and more

### ISSUE THREAD

**Issue by belphegorspn** [nulli0n/ExcellentEnchants-spigot#57]
Darkness Arrows
Applied on Bow or Crossbow
- Chance to launch an arrow with Darkness effect on hit.

Darkness Cloak
Applied on Chestplate / Leggings
- Chance to apply darkness effect to attacker 

Sonic Arrows
Applied on Bow or Crossbow
- Chance to launch a sonic boom arrow that has an extra damage and pierces walls.

**Comment by nulli0n** [comment]
Added for Darkness in v3.5.2
Sonic Boom seems to be a hardcoded thing, so currently skipped.
