### ISSUE TITLE
[Request] Silk Chest enchantment should drop a normal chest if there are no items in it

### ISSUE THREAD

**Issue by zahranicak** [nulli0n/ExcellentEnchants-spigot#59]
Currently, when you break a chest with an axe that has the **Silk Touch** enchantment, it will give you a empty chest, but you can't put this empty chest into any other chests, which is a bit obnoxious.

It would be great if instead of the current behaviour, it would simply drop a regular chest, which you can place into other chests.

**Comment by nulli0n** [comment]
Fixed in v3.5.2
