### ISSUE TITLE
[BUG REPORT]Creeper will destroy the Magma Block formed by 'flame_walker'

### ISSUE THREAD

**Issue by ZherKing** [nulli0n/ExcellentEnchants-spigot#60]
When I enchant 'flame_walker' on my shoes and go to Lava, it will generate a Magma Block. If I destroy it, it will revert to Lava

But when it's blown up by the Creeper, it turns into a Magma Block that can be picked up

https://github.com/nulli0n/ExcellentEnchants-spigot/assets/49807821/04321831-3906-4108-894a-1c5a8f11762e

**Comment by nulli0n** [comment]
Fixed in v3.5.2
