### ISSUE TITLE
The message file is missing a lot?Internal placeholder didn't work?

### ISSUE THREAD

**Issue by RepentStar** [nulli0n/ExcellentEnchants-spigot#62]
## THE MESSAGE FILE 
Why is the message translation file in the repository missing so much content compared to the message file generated by the plugin?
Do I need to follow up with the translation?
## PLACEHOLDER
I've noticed that some of the placeholders for the enchantments don't work. The same %enchantment_trigger_chance% shows up properly in some enchantment entries, and in others the original text "%enchantment_trigger_chance%".
Any ideas on how to solve this please?

**Comment by nulli0n** [comment]
1. Translations are made by users, they may become outdated with updates.
2. Just remove them, they're not a thing anymore for some enchantments.
