### ISSUE TITLE
[BUG REPORT] Elemental Protection enchantment doesn't reduce damage from harm potions while drinking them.

### ISSUE THREAD

**Issue by Kowal9833** [nulli0n/ExcellentEnchants-spigot#63]
Drinking harm potions while having armor with elemental protection equiped deals damage as if the armor wasn't enchanted.

**Comment by nulli0n** [comment]
Not a bug.

**Comment by Kowal9833** [comment]
Wdym? Harm potions count as magic, therefore the damage should be reduced no matter if it was splashed on someone or drank. Or am I not understanding something correctly? I would be glad if you'd help. :)
