### ISSUE TITLE
[Bug Report] placeholder could not display

### ISSUE THREAD

**Issue by xiaozhu2007** [nulli0n/ExcellentEnchants-spigot#66]
<https://github.com/nulli0n/ExcellentEnchants-spigot/blob/4a05fc50bd579403102087caa8a2bdaa79e0a2e4/Core/src/main/java/su/nightexpress/excellentenchants/Placeholders.java#L15>

![)OMEGC1C4B4(}(D51)XW4 N_tmb](https://github.com/nulli0n/ExcellentEnchants-spigot/assets/63779340/6cf75899-18b5-4e40-93e2-f19f54e60e8d)

![}QO~OI}2ZUPPW33BW%D}WJS_tmb](https://github.com/nulli0n/ExcellentEnchants-spigot/assets/63779340/bb5ef9ef-6d3a-4582-93e7-89c9dc4ae9e0)

```
[Kauo7420] 10:54:17
PAPI's ecloud does not have a plugin download for this
```

**Comment by nulli0n** [comment]
Some enchants don't have this placeholder anymore, you can remove it from their description(s).
