### ISSUE TITLE
Is it possible to add compatibility with version 1.16.5?

### ISSUE THREAD

**Issue by yitong2333** [nulli0n/ExcellentEnchants-spigot#67]
Couldn't have found a better plugin than this one

**Comment by nulli0n** [comment]
We prefer to evolve rather than regress.

**Comment by yitong2333** [comment]
666


755398595
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nulli0n/ExcellentEnchants-spigot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月14日(星期一) 晚上11:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nulli0n/ExcellentEnchants-spigot] Is it possible to add compatibility with version 1.16.5? (Issue #67)





 
We prefer to evolve rather than regress.
