### ISSUE TITLE
"Conflicts" meaning

### ISSUE THREAD

**Issue by Chris6ix** [nulli0n/ExcellentEnchants-spigot#68]
Hey, I have a question:

Are the "conflicts" of enchantments just for "balancing" reasons, or are there they actual conflicts that cause issues?
Since the conflict list can be edited, my guess is that they work fine when combined?

**Comment by nulli0n** [comment]
Yes, just for balancing.

**Comment by Chris6ix** [comment]
Alright, thank you.
