### ISSUE TITLE
Doubled Enchants

### ISSUE THREAD

**Issue by EverlastingYT** [nulli0n/ExcellentEnchants-spigot#7]
When I initially have a eEnchant on an item, and add another one with a book, it adds another of the initial eEnchant.
![image](https://user-images.githubusercontent.com/45980432/155854790-ee8612dd-8d68-41ba-af1b-d339c9be1d44.png)

**Comment by EverlastingYT** [comment]
With this one, I initially had Double Strike IV, then I added Exp Hunter V and it added another Double Strike IV. Then I added Scavenger IV and it added another Double Strike IV and Exp Hunter V.

**Comment by nulli0n** [comment]
Plugin conflict
