### ISSUE TITLE
[Bug Report] Regrowth prevents healing with Health Boost

### ISSUE THREAD

**Issue by cowpod** [nulli0n/ExcellentEnchants-spigot#70]
Regrowth causes health to un-heal when you have more than 20, stopping exactly at 20. In this case with Health Boost 2. I've already set `Max_Health: '40.0'` in regrowth.yml, but this doesn't fix the issue. No errors in log, debug enabled.

<img width="1470" alt="Screenshot 2023-08-28 at 23 25 07" src="https://github.com/nulli0n/ExcellentEnchants-spigot/assets/6283258/784fd850-249b-4b91-bd9d-fadbf381fd86">

```
...
    # Level placeholder: %enchantment_level%
    Max_Health: '40.0'
    # Amount of hearts to be restored.
    # You can use formulas/expressions here: https://github.com/nulli0n/NexEngine-spigot/wiki/Configuration-Tips#scalable-sections
    # Level placeholder: %enchantment_level%
    Amount: '0.5'
```

**Comment by nulli0n** [comment]
Unable to reproduce. Works fine on the latest version.
