### ISSUE TITLE
After installing  ExcellentEnchants ，Kill Pillager cant get minecraft:bad_omen buff

### ISSUE THREAD

**Issue by SnivyJ** [nulli0n/ExcellentEnchants-spigot#8]
After installing  ExcellentEnchants ，Kill Pillager cant get minecraft:bad_omen buff

**JAVA VERSION**
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)
OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)

**Windows Version**
Windows11

**Spigot Version**
CraftBukkit version 3442-Spigot-699290c-62d9762 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT)

**Plugins Install**
Plugins (2): NexEngine, ExcellentEnchants

**How to reproduce**
Create new world and find a Pillager captain to kill
He won't get buff and achievements correctly

**Please fix it as soon as possible, which will make the emerald farm of the server unable to run**

**Comment by nulli0n** [comment]
Fixed in 3.1.3
