### ISSUE TITLE
[BUG] Soulbound enchant 

### ISSUE THREAD

**Issue by FurrO2** [nulli0n/ExcellentEnchants-spigot#85]
Hello, I'm using the latest version of NexEngine and Excellent Enchant. I have encountered an issue with Soulbound. I can't enchant items such as bows, crossbows, and fishing rods using the Soulbound enchantment with a Soulbound book and an anvil.

![Capture d’écran 2023-11-13 164958](https://github.com/nulli0n/ExcellentEnchants-spigot/assets/133584837/4e4caf16-758f-46b9-b179-fc98891c22ed)
![Capture d’écran 2023-11-13 165037](https://github.com/nulli0n/ExcellentEnchants-spigot/assets/133584837/5c8a896d-5d58-43b9-b667-d1d974558357)
![Capture d’écran 2023-11-13 165120](https://github.com/nulli0n/ExcellentEnchants-spigot/assets/133584837/71af60fd-de8d-4b57-a8b4-75ef1df2b2b7)

**Comment by FurrO2** [comment]
And also, it's on paper 1.20.1 server*

**Comment by nulli0n** [comment]
Fixed in 3.6.4
