### ISSUE TITLE
[Help] Enchantment description in items

### ISSUE THREAD

**Issue by ImPachecon22** [nulli0n/ExcellentEnchants-spigot#91]
Good morning, I have started using this plugin and I think it can do great, very interesting things, but I need a specific function that I don't know how to enable. I need that when I enchant something with the plugin's enchantments, it also shows below what this enchantment does. Just like in the photo I attached. Thanks in advance.

The photo is this:

![image](https://github.com/nulli0n/ExcellentEnchants-spigot/assets/155078171/a129ce98-9940-40b3-a521-e54a67d49b9d)

**Comment by nulli0n** [comment]
There is already such feature and even enabled by default.
