### ISSUE TITLE
[BUG] Divine Touch with custom Spawner

### ISSUE THREAD

**Issue by FurrO2** [nulli0n/ExcellentEnchants-spigot#94]
Hello, i have some issues with the enchantement Divinetouch.
When a custom monster spawner is broken, the monster type, once replaced, is changed to a non-custom version.

https://drive.google.com/file/d/1tiJdr5mP1nYDOVBQ0SykpshJlEN7d9ji/view?usp=sharing

the logs : https://log.mtxserv.com/v4XYdTa

using paper 1.20.1 and version 3.6.4 of excellent enchant

**Comment by nulli0n** [comment]
Fixed in v4.2.1
