### ISSUE TITLE
Disable enchants in reigon [Worldguard]

### ISSUE THREAD

**Issue by bobhenl** [nulli0n/ExcellentEnchants-spigot#97]
Hi, is it possible to disabel enchants in region? For example, flare enchant completely ignores the regions... and mobs spawned with this enchant can put torches everywhere in regions... I think it can be in player's claims as well

**Comment by nulli0n** [comment]
Enchantments are using Bukkit events to simulate player actions where necessary. There is more likely an issue in your WorldGuard setup.

You can disable mobs spawning with this enchantment in enchantment config.
